project_name: finetuning
random_state: 2022
lr: 1.0e-3
batch_size: 32
test_batch_size: 64
num_workers: 8
n_epochs: 12
weight_decay: 1.0e-6
label_smoothing: 0.0
optimizer: adamw
lr_scheduler: cosineannealing
severity: 3

imbalanced: true

# =========================== MODEL =====================
model_type: "timm"
model_name: "efficientnet_b0"
input_size: 256
test_input_size: 256
model_ckpt: null
drop_rate: 0.2
hidden: []